### ISSUE TITLE
Changes to ngModel are not propagated to editor after initial set

### ISSUE THREAD

**Issue by olso** [KillerCodeMonkey/ngQuill#10]
I guess it's the same as #2. It's like you deliberately do this...

https://github.com/KillerCodeMonkey/ngQuill/blob/master/src/ng-quill.js#L189
https://github.com/KillerCodeMonkey/ngQuill/blob/master/src/ng-quill.js#L201

Why man?

**Comment by KillerCodeMonkey** [comment]
If you want to manipulate the editor content, you should do it via the editor object.
The model-binding is only something like a hack, to work with default values to fill in the editor.

you can listen to the: 
editorCreated event
$scope.$on('editorCreated', function (event, editor) {});

and use the quill API to set the editor value.
http://quilljs.com/docs/api/#quillprototypesethtml

like you see in my directive:
ngModel.$setViewValue(editor.getHTML());

i set the model value if you type in the editor and i do not want to create unnecessary "cycles".
