### ISSUE TITLE
Destroying all editors on `$locationChangeSuccess`

### ISSUE THREAD

**Issue by khashayar** [KillerCodeMonkey/ngQuill#12]
I ran into a bug where the editor doesn't render correctly whenever I try to load it for more than once. I debugged the code and found out that this part removes the editor just after it's created:
```javascript
// reset all quill editors (to not flood window object works only with ui-router)
$rootScope.$on('$locationChangeSuccess', function () {
  if ($window.Quill && $window.Quill.editors && $window.Quill.editors.length) {
    angular.forEach($window.Quill.editors, function (editor) {
      editor.destroy();
    });
  }
});
```
Probably some incompatibility with my UI router state's config!

I commented the code and now everything works ok. Just wondering what's the reason for this clean-up and why not only cleaning up the editor that was created by current directive instance and not removing all the editors present on $window. I'd suggest removing the `$locationChangeSuccess` part and adding following code inside `ngQuillEditor` directive:
```javascript
element.on('$destroy', function() {
  editor.destroy();
});
```

Please let me know if it looks good to you and then I can do a PR for it.

**Comment by KillerCodeMonkey** [comment]
This whole cleaning stuff up is only there because i needed it in some
projects. Feel free to change it if necessary or buggy.

Thanks

PS: looks well;)
Am 15.06.2015 13:52 schrieb "Khashayar Hajian" <notifications@github.com>:
