### ISSUE TITLE
Add test cases

### ISSUE THREAD

**Issue by KillerCodeMonkey** [KillerCodeMonkey/ngQuill#15]
Any body ??? ^^

**Comment by tranbenny** [comment]
I can help with this. Is there a testing framework you wanted to use, otherwise I was going to use jasmine

**Comment by KillerCodeMonkey** [comment]
that would be awesome!

and jasmine is fine 👯

**Comment by tranbenny** [comment]
sounds good, Ill submit a PR soon

**Comment by KillerCodeMonkey** [comment]
thanks. i try to check them on sunday + connection to travisci.
