### ISSUE TITLE
Npm release

### ISSUE THREAD

**Issue by MikaAK** [KillerCodeMonkey/ngQuill#16]
Is there an NPM release for this? For people using webpack or similar without bower!

**Comment by KillerCodeMonkey** [comment]
Try to handle it tomorrow

**Comment by KillerCodeMonkey** [comment]
https://www.npmjs.com/package/ng-quill

npm install ng-quill

**Comment by KillerCodeMonkey** [comment]
@MikaAK 
i added npm dependencies for angular and quill
