### ISSUE TITLE
Using Quill API Methods with ngQuill

### ISSUE THREAD

**Issue by hareeshr** [KillerCodeMonkey/ngQuill#19]
Is it possible to call a method for Quill?
for eg.
editor.setHTML('Hello World');

With what should I replace 'editor' to work with ng-quill? This is important for me because I'm using a dynamic ng-model.

**Comment by KillerCodeMonkey** [comment]
The ngQuill should trigger an angularjs event if the editor is created called `editorCreated`. As parameter you get the editor instance.

```
$scope.$on("editorCreated", function (event, editor) {
  editor.setHTML("Hello World");
});
```

**Comment by hareeshr** [comment]
For my case, I have 2 different editors, with separate models.
and I want to trigger setHTML on click of a button. ie. not an initial value

Thanks for quick response though :-)

**Comment by KillerCodeMonkey** [comment]
two approachs:
1. add your button-function only to the $scope if the event gets called.
2. store the editor object in a local variable in your controller, if the event gets called --> Check if the editor is created in your "button function" to avoid js error accessing undefined editor variable.

**Comment by hareeshr** [comment]
Hey,
The button I used had some other jobs too, if the editor is not created, since the editor was to load via AJAX.
But storing it to a local variable, will definitely work with my case. 

Thanks a lot... keep going...(Y)
