### ISSUE TITLE
Custom font size labels

### ISSUE THREAD

**Issue by matikun86** [KillerCodeMonkey/ngQuill#21]
Sorry if it's already done but I couldn't find it explained.
I would like a way to customize some things, i.e. the toolbar font-size labels. As right now they are always four and they're always 10px, 13px, 18px and 32px

I think the more flexible approach would be to allow users to use their own template.

**Comment by KillerCodeMonkey** [comment]
this has nothing to do with the angular module.
You can do this with quill-themes.

There you can overwrite the css-classes to build your own themes.
To use a custom theme read this:
http://quilljs.com/docs/themes/

**Comment by matikun86** [comment]
I think you can't do what I'm saying with Quill themes as they are css files to customize the way it *looks* and I'm talking about changing the ```<option>``` tags that are in the ```<select class="ql-size" ...>``` element.

Right now the directive is configured as:
```Javascript
templateUrl: 'ngQuill/template.html'
```
and down below in the ```return $templateCache.put('ngQuill/template.html',``` it is hardcoded to:
```Javascript
'<select title="{{dict.size}}" class="ql-size" ng-if="shouldShow([\'size\'])">' +
  '<option value="10px">{{dict.small}}</option>' +
  '<option value="13px" selected="">{{dict.normal}}</option>' +
  '<option value="18px">{{dict.large}}</option>' +
  '<option value="32px">{{dict.huge}}</option>' +
'</select>' +
```

I was saying that would be nice to have a parameter to send font-size options as value-label objects. I.E.:
```Javascript
[{
  label: 'Paragraph',
  value: '14px'
}, {
  label: 'Subtitle',
  value: '18px'
}, {
  label: 'Title',
  value: '24px'
}]
```

Or to be able to configure another template file path and let each user deal with their own complex and exhausting html files :stuck_out_tongue_closed_eyes:

**Comment by KillerCodeMonkey** [comment]
sry my fault.

feel free to implement it your self and send me a pull request ;)

**Comment by matikun86** [comment]
@KillerCodeMonkey No problem!
I'm working in a PR right now. Maybe is not as good as to merge it as is but I hope in best case scenario it's an approach you can tweak.
I'll send you the PR today or tomorrow.

Thank you very much for the quick feedback!

**Comment by matikun86** [comment]
[PR created for this issue](https://github.com/KillerCodeMonkey/ngQuill/pull/22)

**Comment by KillerCodeMonkey** [comment]
i will change your code a little bit --> instead of working with the rootScope i will add a configProvider, that can be extended and clean configured.

you added $rootScop.message why?

**Comment by KillerCodeMonkey** [comment]
added config provider and created a new release

**Comment by matikun86** [comment]
Oh no, I just used $rootScope because I needed to test it because otherwise I would have added a new controller to do that. But wasn't supposed to be clean at all.
```i will change your code a little bit --> instead of working with the rootScope i will add a configProvider, that can be extended and clean configured.``` :+1: awesome

**Comment by arunvenugopal11** [comment]
@matikun86 @KillerCodeMonkey Hey guys, I'm wondering how I can add custom font size dropdown into the toolbar. Is there a demo I can refer to? Thanks!

**Comment by KillerCodeMonkey** [comment]
I think there is an example at The quilljs playground. You can adapt that

Arun Venugopal <notifications@github.com> schrieb am Mi., 18. März 2020,
21:04:
