### ISSUE TITLE
Loading src/ng-quill.js

### ISSUE THREAD

**Issue by Binnsler** [KillerCodeMonkey/ngQuill#24]
I'm having trouble loading the ng-quill script like you have in "demo.html". 

In my jade file it looks like: 

"script(type="text/javascript" src="src/ng-quill.js")"

But I keep getting a GET error.

You can see the jade template under "views/": https://github.com/Binnsler/TheOfficialGalacticCollective/tree/master

I keep see a GET error but can't tell if it's me calling it in a weird way or if something is weird with the module.

Any chance you could help out?

**Comment by KillerCodeMonkey** [comment]
You need to load it from the node_modules folder.

/node_modules/ng-quill/src/ng-quill.min.js or something similar :)

In my demo.html the src-folder is a sibling dir. But in your case you
installed it via npm.

**Comment by Binnsler** [comment]
Thanks for your help, I definitely loading it from the wrong place.

Works great now!

Thanks,

Jamie
