### ISSUE TITLE
model of ng-quill-editor doesn't updated dynamically without typing in editor. 

### ISSUE THREAD

**Issue by mir-nawaz-10p** [KillerCodeMonkey/ngQuill#25]
# issue 
When model of ng-quill-editor doesn't updated dynamically without typing in editor. 

update model at run time without typing it doesn't update model. 

Here is a link to a similar type issue. 
http://stackoverflow.com/questions/29731771/ng-quill-text-editor-only-updates-once

please enable two way data binding

In the latest version of ng-quill 
The $window scroll is moving when we have fixed height for ".editor-container".

**Comment by KillerCodeMonkey** [comment]
I do not want two-way data-binding for that to not destroy the original quill-editor behavior.
To solve your Problem:
1. After the editor is created you get the editor instance via an angularjs event "editorCreated". 
``` $scope.$on("editorCreated", function (event, quillEditor) { // store editor instance }); ``` 
2. If you change the model programmatically --> you can trigger to refresh the editor by using the quill-functions http://quilljs.com/docs/api/#quillprototypesethtml
``` quillEditor.setHTML(newValue); ```

Please try this approach and let me know if this works for you.

Thanks and greets.

**Comment by mir-nawaz-10p** [comment]
Thanx. It worked for me . 
But the scroll issue still persists. 
I want a fixed height ".editor-container" div. 
but it affects the scroll behavior of the of parent div and  ".editor-container" div. 
also when clicking on toolbar the  ".editor-container" div's scroll moves to top on IE and FF.
Thanx for the help 
Regards
Mir

**Comment by KillerCodeMonkey** [comment]
the scroll behavior sounds like a quill editor problem.
I do not add additional css stylings. I only upgraded quilljs and angularjs in the latest version.

There is a workaround for that:
https://github.com/quilljs/quill/issues/288

**Comment by mir-nawaz-10p** [comment]
Thanks 
The above linked worked for the scroll behavior
