### ISSUE TITLE
Creating a custom module Example

### ISSUE THREAD

**Issue by aliirz** [KillerCodeMonkey/ngQuill#26]
Hello I am trying to register a word counter module for my implementation. This is how I am trying it:

```
    $scope.$on("editorCreated", function (event, editor) {
        editor.setHTML("Hello WWQds");
        editor.registerModule('counter', function  (quill, options) {
          
        });
    });
```

However I keep getting the following error:
```
Error: editor.registerModule is not a function. (In 'editor.registerModule('counter', function  (quill, options) {

        })', 'editor.registerModule' is undefined)
http://localhost:9000/app/dashboard/newdocument/newdocument.controller.js:10:30
$emit@http://localhost:9000/bower_components/angular/angular.js:16238:38
http://localhost:9000/bower_components/ngQuill/src/ng-quill.min.js:1:3498
http://localhost:9000/bower_components/angular/angular.js:17855:36
completeOutstandingRequest@http://localhost:9000/bower_components/angular/angular.js:5507:15
http://localhost:9000/bower_components/angular/angular.js:5784:33
```

I know how quill works without angular but I have no clue on how to create my custom modules using ng-quill. Can someone please provide an example. 

Thanks

**Comment by KillerCodeMonkey** [comment]
Hey there,

look in the documentation of quilljs. You have to call the register
function on the global Quill object not the editor instance.

Hope that helps.

Greets you codemonkey

**Comment by KillerCodeMonkey** [comment]
any updates here @aliirz ???

if there is nothing else, i will close this issue

**Comment by aliirz** [comment]
no unfortunately I am a noob and cannot figure out where the global Quill object is :(

**Comment by KillerCodeMonkey** [comment]
For that you can look in my source code --> stc/ng-quill.js

there is this line `editor = new Quill(element[0].querySelector('.advanced-wrapper .editor-container'), config);`

To create a new editor instance --> so if you are added ngQuill as a dependency in your angular app and included quilljs in your index.html. You can simply call `Quill.register()`. `Quill` is the shortcut for `window.Quill`.

For deeper explanation:
quilljs --> adds Quill-object to your window
ngquill --> only sets a wrapper around it to work easy with it in angularjs (with some benefits like translations and so on...)

You question is more a quill js question then a ngquill issue.

**Comment by aliirz** [comment]
Thank you @KillerCodeMonkey I tried the Quill.register approach in my app.js code as well first. For some strange reason it did not work. Its ok though I figured it out now. I was passing the module in my controller. Makes sense. Thank you

**Comment by KillerCodeMonkey** [comment]
no problem. nice that you get it work :+1:

**Comment by dbdario025** [comment]
@aliirz could you please provide an example of the use of Quill.register?

**Comment by KillerCodeMonkey** [comment]
it is the same like with native javascript. Nothing special... 
like in the demo.html https://github.com/KillerCodeMonkey/ng-quill/blob/develop/demo.html --> after you load quilljs you can access the global quill object ;) and call methods on it.

further information you get in the quilljs documentation

**Comment by dbdario025** [comment]
Thanks @KillerCodeMonkey, I am a beginner with respect to this issue of text editors and indeed with angular :). I need to modify the size of the video and the images in the editor, I know that the libraries that others have made can be used easily, which is not how to do it ...
I do not want you to do the work for me, but if you can give me an example or a guide on how to get it, I will be very grateful.

This is what I am doing:
app.js
```
var courseApp = angular.module("course_main", [
    "directives", "services", "controllers",
    "ngMaterial", "ngAria", "ngAnimate",
    "ui.router", "ngRoute", "ngCookies", 
   "angular-loading-bar", "user.Services", 
   "course.Services", "controller.Courses.main", 
   "angulartics.google.analytics","froala","ngQuill"]);

courseApp.config(['ngQuillConfigProvider', function (ngQuillConfigProvider) {
    ngQuillConfigProvider.set(null, null, 'custom placeholder')
}]);
```
controller.js
```
AppControllers.controller('blogCtrl', ["$scope", "blog.model", "$stateParams", "util", function ($scope, blog, $stateParams, util) {
        $scope.journals = [];
		
	    $scope.customOptions = [{
			import: 'attributors/style/size',
			whitelist: ['14', '16', '18', 'small', 'large', 'huge']
		}]
		$scope.customModules = {
			toolbar: [
				[{'size': [false, '14', '16', '18']}]
			]			
		};
        //I think that here i can add the other libraries as a module, but i don't know how to do it.
       var quill = new Quill('#editor', {  //This line show me an error in console that says Quill is not defined
         theme: 'snow',
         modules: {
            imageResize: {
             displaySize: true
         }
      }
    });
}]);
```
index.html
in this file, only i know that loading the libraries and CSS files will be fine.
 
```
<link href="https://cdn.quilljs.com/1.3.5/quill.snow.css" rel="stylesheet">
<link href="https:////cdn.quilljs.com/1.3.5/quill.bubble.css" rel="stylesheet">		

<script type="text/javascript" src="https://cdn.quilljs.com/1.3.1/quill.js"></script>
<script type="text/javascript" src="/resources/js/plugins/ng-quill/src/ng-quill.js"></script>
<script src="/resources/js/plugins/ng-quill/image-resize.min.js"></script>

 <div class="form-group">
        <label>Content</label>
	<ng-quill-editor ng-model="blog.comms" placeholder="write here" ></ng-quill-editor>
         <p ng-show="journalForm.comms.$invalid && !journalForm.comms.$pristine" class="help-block">Please write content in text Editor.</p>
 </div>
```

But when I add an Image this doesn't work with resize because I have console errors causing angular failure.

I hope that you can help me.

Thanks and regards

**Comment by deshario** [comment]
@dbdario025  Did u got it ?
