### ISSUE TITLE
No buttons, no textarea delimitation

### ISSUE THREAD

**Issue by SebastienRitz** [KillerCodeMonkey/ngQuill#3]
Hi, 
I tried to used your directive for Quill but there is a problem.
The editor looks like this : 
![capture d ecran 2015-01-11 a 17 26 25](https://cloud.githubusercontent.com/assets/6841511/5695897/076eb034-99b7-11e4-9002-92786b7a1930.png)
I used angular 1.3.1 and my code is the same you wrote in your home page
Any idea what is going wrong ?
Thank you.
Seb

**Comment by KillerCodeMonkey** [comment]
Could you create a codepen or something like this with your code?
Or are there some error messages in your console? (Chrome press f12 and
click on console)
Am 11.01.2015 17:27 schrieb "SebastienRitz" <notifications@github.com>:

**Comment by jziggas** [comment]
This just happened to me a couple days ago. I was expecting the bower.json to include the stylesheets by default but it does not. Adding them manually(both base.css and snow theme) fixed everything.

**Comment by KillerCodeMonkey** [comment]
Strange... When i build this thing the CSS files were included.
Am 13.01.2015 00:43 schrieb "Joshua Ziggas" <notifications@github.com>:

**Comment by SebastienRitz** [comment]
jziggas were right the css were not added to my html page. Thanks for reply !
