### ISSUE TITLE
Provide demo in gh-pages branch

### ISSUE THREAD

**Issue by fracz** [KillerCodeMonkey/ngQuill#32]
It would be nice :-) https://pages.github.com/

**Comment by KillerCodeMonkey** [comment]
ugly but working:

http://killercodemonkey.github.io/ngQuill/demo.html

;)

**Comment by fracz** [comment]
Great! Don't forget to mention the link in the README :-)

**Comment by KillerCodeMonkey** [comment]
done in master branch
