### ISSUE TITLE
Content of the editor is cleared on Ctrl+Z

### ISSUE THREAD

**Issue by fracz** [KillerCodeMonkey/ngQuill#33]
1. Create the editor `<ng-quill-editor ng-model="content"></ng-quill-editor>` when `content` have some text in it.
2. Enter the editor.
3. Press <kbd>Ctrl</kbd>+<kbd>Z</kbd>.
4. Editor is empty.

**Comment by KillerCodeMonkey** [comment]
hey fracz, this is more likely a problem with the quilljs editor:
http://quilljs.com/

**Comment by fracz** [comment]
Nope, I have checked it and the demos on http://quilljs.com/ do not behave that way. I suppose that Quill treats the first content update from `ng-model` as an operation that it can undo.

**Comment by KillerCodeMonkey** [comment]
wuuuuuush real fast response ^^.

You have the possibility to set the initial value via QuillJS-API --> if the editor is created a angularjs event is triggered, where you get the editor instance. With that you can call the editor.setHTML, ...getHtml, ... functions to work with the editor.

So you can avoid the usage of the ngModel. I think there is no way to prevent this behavior with ngModel. :/

**Comment by fracz** [comment]
I can not avoid the usage of the ngModel :-(

    Controller 'ngModel', required by directive 'ngQuillEditor', can't be found!

**Comment by KillerCodeMonkey** [comment]
try to simply add a not initialized model, which you are not using afterwards

**Comment by fracz** [comment]
I got it!

After the editor is created (in the `editorCreated` event handler) I have added:

    quillEditorInstance.getModule('undo-manager').clear()

And now it behaves as expected.

I would be grateful if you could add this to the plugin (just before posting the `editorCreated` event?).

**Comment by KillerCodeMonkey** [comment]
@fracz 

https://github.com/KillerCodeMonkey/ngQuill/releases/tag/1.4.1

**Comment by fracz** [comment]
Confirm - 1.4.1 fixes this issue. Thank you!
