### ISSUE TITLE
Cannot apply styles to selected text with toolbar

### ISSUE THREAD

**Issue by fracz** [KillerCodeMonkey/ngQuill#34]
1. Go to the [demo](http://killercodemonkey.github.io/ngQuill/demo.html).
1. Enter "Lorem ipsum".
1. Select "ipsum".
1. Press "B" (bold) button on toolbar.
1. Text is deselected and styles are not applied.

**Comment by KillerCodeMonkey** [comment]
Works for me? 

![quill_bold](https://cloud.githubusercontent.com/assets/2264672/14018735/856e4b90-f1cf-11e5-9a40-598b7909a182.png)

**Comment by fracz** [comment]
![](http://home.agh.edu.pl/~fracz/ng-quill.gif)

Chrome, Windows

**Comment by KillerCodeMonkey** [comment]
and tested on windows 8.1 and chrome --> it works :)

**Comment by fracz** [comment]
Strange. After I got home I cannot reproduce it anymore. I will reopen if this happens again.

**Comment by fracz** [comment]
I can confirm that this is reproducible after using the editor _for a while_. However, I have not found anything concrete yet...

**Comment by KillerCodeMonkey** [comment]
cool, if you have an idea have to reproduce it, let me know. 

In the nearer future i will look into QuillJS 1.0 Beta. Maybe i will create a new Version based on this beta (if it is stable enough)
