### ISSUE TITLE
Using multiple instances on one page

### ISSUE THREAD

**Issue by Cordobo** [KillerCodeMonkey/ngQuill#35]
Hello,
first, thanks for your work on building a wrapper for quill.js, it works like a charm.

Unfortunately, there is an issue with multiple editors on one page (or within one controller). Quill.js attaches the default styles multiple times to the HEAD of the HTML file. I fixed it by adding quill.js "styles"[1] attribute to the directives scope [2], passing "true" or "false" to "editor-styles" (defaults to "false").

I can open a PR if you think it helps others as well.

[1] http://quilljs.com/docs/configuration/
[2] https://github.com/Cordobo/ngQuill/commit/b0af6f63a2d5a936eeaf141ba6cd8726aa2196d6

**Comment by KillerCodeMonkey** [comment]
sounds good. you can open a pull request. but please to the develop-branch (i am using git-flow) and do not forget to add the key to the readme.md :).

I will release a new verison afterwards.

Thanks for contributing :+1:

**Comment by Cordobo** [comment]
Hi Bengt,

I added the description to the readme and opened the PR.
