### ISSUE TITLE
Touched state

### ISSUE THREAD

**Issue by j-a-m-l** [KillerCodeMonkey/ngQuill#40]
Currently ngQuill marks the field as untouched initially but it doesn't mark it as touched after an interaction.

I've read the Quill documentation and it doesn't listen to click or bluer events, so I guess that this could be implemented using something like this `angular.element(field).one('click'...`.

@KillerCodeMonkey, what do you think about this?

**Comment by KillerCodeMonkey** [comment]
> Currently ngQuill marks the field as untouched initially but it doesn't mark it as untouched after an interaction.

What is wrong with it?
If you make an interaction it is touched?

Sry, if i do not get it.

**Comment by j-a-m-l** [comment]
Sorry, I've updated my comment. I was talking about the necessary change from "untouched" to "touched" after the first interaction.

From https://docs.angularjs.org/api/ng/type/ngModel.NgModelController
>  A model is considered to be touched when the user has first focused the control element and then shifted focus away from the control (blur event).

So, the problem is that after that first interaction, the model is marked as untouched instead of touched.

**Comment by KillerCodeMonkey** [comment]
Okay, now i know what you mean :)
Thank you for your clarification.

I will dig into it... hopeful very soon

**Comment by j-a-m-l** [comment]
Ok, if you want I could help you. Any ideas?

**Comment by KillerCodeMonkey** [comment]
@j-a-m-l 
i committed a little thing in develop-branch.
Model should be set to touched after the editor lost focus.

Please check if this is the wanted behavior, Thanks.

If everything is fine, i will create a new release tag
