### ISSUE TITLE
ngModel change tracking problem with if(newText)

### ISSUE THREAD

**Issue by marcoleong** [KillerCodeMonkey/ngQuill#42]
**In order to re-produce the issue**

visit the following JSBin
[http://jsbin.com/quzaco/edit?html,js,output](http://jsbin.com/quzaco/edit?html,js,output)

**cannot empty text in Quill editor**
1. Type random text in Quill editor
2. Click "Clear (without space)"
3. Template was updated, but not the content inside Quill editor

**can empty text in Quill editor**
1. Type random text in Quill editor
2. Click "Clear (with space)"
3. Template was updated, as well inside Quill editor

As I want to have the content empty, I would set `content = ''`, but it only work with `content = ' '`. The line that determine the update is here.
[https://github.com/KillerCodeMonkey/ngQuill/blob/1.4.4/src/ng-quill.js#L276](https://github.com/KillerCodeMonkey/ngQuill/blob/1.4.4/src/ng-quill.js#L276)

The issue is JS has evaluate `''` string as `falsy`. I wonder if it would better to change to `undefined` checking instead?

[http://stackoverflow.com/questions/27509/detecting-an-undefined-object-property](http://stackoverflow.com/questions/27509/detecting-an-undefined-object-property)

Even it has a very simple workaround, but will you still consider changing the conditional statement inside?

Any thoughts?

Thanks !

**Comment by KillerCodeMonkey** [comment]
if you want to fix this make a pull requests on the develop branch :)

Or as workaround --> you can get the editor instance through the "editorCreated" event.
So on button click you can set the content "editor.setHTML()" directly with the QuillJS API:

http://quilljs.com/docs/api/#quillprototypesethtml

**Comment by KillerCodeMonkey** [comment]
released a new version. read the breaking changes section in the readme.
now based on angularjs 1.5.6 the editor is a component now.

I extendet the demo: --> init value is set and after 3 seconds the value is changed through the model.
The clear button clears the editor and model content, correctly
http://killercodemonkey.github.io/ngQuill/demo.html
