### ISSUE TITLE
Upgrade to quill 1.x

### ISSUE THREAD

**Issue by KillerCodeMonkey** [KillerCodeMonkey/ngQuill#49]
should be done!

**Comment by mcblum** [comment]
This would be awesome!!!

**Comment by rodneyjoyce** [comment]
+1 (Looks like the latest version supported is  v0.20.1

**Comment by KillerCodeMonkey** [comment]
Will not upgrade to quilljs 1 or 2 because html support is kicked off.
But i think in most cases people want to render the produced html in their side without rendering an quilleditor each time.

**Comment by vukoje** [comment]
You're just gonna stick with obsolete version forever?

**Comment by mcblum** [comment]
@vukoje while I agree, that's the beauty of open source software -- you're free to do whatever you want with it. If you don't like @KillerCodeMonkey's decision fork it, change it how you think it should be changed, give credit and tell all of us about it :)

**Comment by vukoje** [comment]
@mcblum true true...  I just wanted to check.  If I end up codung my own I will definitely share it with you guys.  

@KillerCodeMonkey do you maybe have some draft version of upgraded dirrctive I could start from?

**Comment by KillerCodeMonkey** [comment]
i would create a new version with quill 1.0 but i do not see how to provide this new version without destroying everyones projects, which not fixed version.

Because like i said: there is no way to retrieve or set the editor content as html.
If there is a non-hacky way to solve this --> let me know.

@vukoje it is not that difficult --> try the new quilljs version, transform it to an angularjs component and make it configurable.
