### ISSUE TITLE
vendor.js:76925 TypeError: Cannot read property 'trim' of undefined

### ISSUE THREAD

**Issue by mcblum** [KillerCodeMonkey/ngQuill#50]
Any ideas what could be causing this error? Thanks for putting this package together!

**Comment by rodneyjoyce** [comment]
I am getting something similar. Just evaluating different HTML Editors and followed the set up instructions. The editor appears but I get this error:

angular.js:13920 TypeError: Cannot read property 'trim' of undefined
    at Quill.setHTML (http://localhost:62674/node_modules/quill/dist/quill.js:10527:14)
    at g (http://localhost:62674/node_modules/ng-quill/src/ng-quill.min.js:1:2254)
    at http://localhost:62674/node_modules/ng-quill/src/ng-quill.min.js:1:4094
    at Scope.$emit (http://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular.js:17932:33)
    at .<anonymous> (http://localhost:62674/node_modules/ng-quill/src/ng-quill.min.js:1:4579)

**Comment by Cordobo** [comment]
@mcblum It looks as the directive does not provide a default for the editors ngModel, the value is undefined and you get the type error (same here).

To solve this, I added an empty string as the initial value and the type error was gone.
If your your **ngModel** is `ng-model="message"`, set:

`$scope.message = '';`

If you get an async value from a service, you can use $timeout to replace the empty string:

> $timeout(function () {
> $scope.message = 'Async Test content';
> console.log($scope.message);
> }, 3000);

**Comment by Cordobo** [comment]
I fixed this issue in the development branch. Hope @KillerCodeMonkey has time to merge this into master.
