### ISSUE TITLE
Is the demo broken?

### ISSUE THREAD

**Issue by rodneyjoyce** [KillerCodeMonkey/ngQuill#51]
Hello,

On this demo page:  http://killercodemonkey.github.io/ngQuill/demo.html

When you highlight text and click on B (Bold) the curos jumps away, and when you select a different color it does not work. 

Is this a known issue or am I doing something wrong on the demo?

**Comment by KillerCodeMonkey** [comment]
strange never mentioned such a problem Oo

Maybe i am able to upgrade quill to 1.5 (but this will need many changes) in the next weeks.
And such issues are gone

**Comment by KillerCodeMonkey** [comment]
I have updated the demo and i only could reproduce it once

Mac OSX + Chrome

Any more information about your browser + sys?
Does it occur every time or only sometimes --> You can see the html-output below the editor, maybe it produces invalid HTML

**Comment by rodneyjoyce** [comment]
I am using Windows 10 and Chrome browser. I have just updated to the latest  (53.0.2785.143 m) and it seems to work consistently now. (It was not working before I updated, but seems to be all good now, thanks)

**Comment by KillerCodeMonkey** [comment]
no problem. feel free to reopen the issue if you strange things happens again.

Thanks!
