### ISSUE TITLE
Is the Travis CI config broken? 

### ISSUE THREAD

**Issue by Cordobo** [KillerCodeMonkey/ngQuill#53]
Hello @KillerCodeMonkey 

Unfortunatelly I have no experience with Travis, but the error message looks like if there's some issue :)

> rake aborted!
> No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)

[Travis CI Build](https://travis-ci.org/KillerCodeMonkey/ngQuill/builds/164146245)
[Pull Request Result](https://github.com/KillerCodeMonkey/ngQuill/pull/52)

EDIT: Looks like the missing **.travis.yml** file is causing this issue

**Comment by KillerCodeMonkey** [comment]
i deactivated travis. thanks.
