### ISSUE TITLE
Using Quill with bower

### ISSUE THREAD

**Issue by madhurangaonbit** [KillerCodeMonkey/ngQuill#54]
I tried to use Quill with bower. However, I keep getting Quill is not defined all the time.
I did same as you have mentioned on the readme file.

`Uncaught ReferenceError: Quill is not defined              ng-quill.min.js:1 `

**Comment by KillerCodeMonkey** [comment]
Did you include Quill editor in your head or body before ngQuill?

**Comment by madhurangaonbit** [comment]
It is automatically loaded by grunt. seems Quill come after ngQuill.

**Comment by KillerCodeMonkey** [comment]
Yeah then you should change the order ;)

**Comment by dnlmzw** [comment]
I looked around in the QuillJS repo [Re-add built distribution for v1.0 #926](https://github.com/quilljs/quill/issues/926) where the same issue is being discussed. I managed to get a pre-built version by adding: `https://github.com/quilljs/quill/releases/download/v1.1.5/quill.tar.gz` to the Bower path, which got me a /dist folder.

Unfortunately I'm now stuck with `app.component is not a function` when I include ng-quill.
