### ISSUE TITLE
ngQuill Format buttons not working in ngQuill-1.4.4

### ISSUE THREAD

**Issue by optikool** [KillerCodeMonkey/ngQuill#55]
Hi,

I'm using ngQuill-1.4.4. I believe this is the latest version that doesn't require upgrading to Angular 1.5 and I'm using this version because I cannot upgrade to 1.5. In Chrome on Windows 10, the format buttons, B, U, Link, etc are not working. When I highlight the text and click on any of the buttons, the text becomes unhighlighted and doesn't get formatted. The link box doesn't appear when trying to create a link. This problem also happens with the demo included in the zip. This works fine in IE and also Chrome on Mac. Can you tell me if this has been fixed in a later version of ngQuill and if so, how can I modify this version to work as the people that will be using this editor will be primarily on Windows?

Thanks
Dana

**Comment by KillerCodeMonkey** [comment]
Sadly i am not able to test it on a windows machine.

But you can easy try it in the online demo: http://killercodemonkey.github.io/ngQuill/demo.html

**Comment by KillerCodeMonkey** [comment]
close because no response at all
