### ISSUE TITLE
quill compatible version with ngQuill

### ISSUE THREAD

**Issue by mu7amed-abdelfata7** [KillerCodeMonkey/ngQuill#59]
What is the higher version of quill compatible with ngQuill? because I used quill v1.1.1 except for v0.20.1 with ngQuill in the demo which you made and these error comes up:

![s](https://cloud.githubusercontent.com/assets/8555914/19625056/524ad0f8-990e-11e6-8433-759303f58e22.PNG)

**Comment by KillerCodeMonkey** [comment]
works only with 0.20.1 and below.
