### ISSUE TITLE
Multi editor instances are problematic

### ISSUE THREAD

**Issue by hantsy** [KillerCodeMonkey/ngQuill#60]
Currently the ng-quill tried to bind Quill editor to a single editor by css selector. If I added more than one editors in one pages, It will be problematic.

**Comment by KillerCodeMonkey** [comment]
it is not problematic --> it is an component und based on the element name.

there is an optional attribute "name" where you can register your editor with a name --> after Editor creation you can grab the instance and the name.

**Comment by hantsy** [comment]
@KillerCodeMonkey  Thanks. I will try it later.

**Comment by hantsy** [comment]
Hi @KillerCodeMonkey , confirm the problem in my case.

You defined `name`  bindings  like this:

```
'name': '@?',
```

It does not support expression, in my application, I used editor in *ng-for* iteration, I have to make sure it generates an unique editor name for every item, right?

I set `name= 'editor{{$index}}'` etc, it does not work.

**Comment by hantsy** [comment]
@KillerCodeMonkey  or you have some good idea to overcome this barrier currently.

**Comment by KillerCodeMonkey** [comment]
name='editor{{$index}}' should work in my opinion {{index}} should be evaluated before passing to the quill directive.

Could you inspect your HTML in the browser if {{$index}} is replaced with 0, 1, ...?

**Comment by hantsy** [comment]
@KillerCodeMonkey  Sorry for my mistake, maybe the error caused by importing Quill 1.x. I have not digged  into the details.

**Comment by KillerCodeMonkey** [comment]
no probs ;)
