### ISSUE TITLE
QuillJS 1.1.x support 

### ISSUE THREAD

**Issue by hantsy** [KillerCodeMonkey/ngQuill#61]
It seems this ngQuill directive is locked to 0.20.1. When I used the latest QuillJS 1.1.x, it does not work, all toolbar disappeared.

**Comment by KillerCodeMonkey** [comment]
please use search through closed issues. 

This version only works with 0.20.1.

QuillJS 1.x has a changed api and uses other technologies.

**Comment by hantsy** [comment]
@KillerCodeMonkey  Thanks
