### ISSUE TITLE
Errors when using Quill 1.1

### ISSUE THREAD

**Issue by mindscratch** [KillerCodeMonkey/ngQuill#63]
I'm trying to use Quill 1.1 with ngQuill 1.5.3 but I'm getting an error:

> Cannot import modules/link-tooltip. Are you sure it was registered?

The HTML looks like this:

` <ng-quill-editor ng-model="message" toolbar="true" link-tooltip="true" image-tooltip="true" toolbar-entries="font size bold list bullet italic underline strike align color background link image" editor-required="true" required="" error-class="input-error"></ng-quill-editor>`

**Comment by KillerCodeMonkey** [comment]
Heyho,

please use the search function next time --> no support of QuillJS 1.x.

They changed their API and kicked out HTML-Support. And that is a no go for me.
All my projects are based on easy write and reading HTML ;)
